version: '3.8'
services:

  webapp:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://mongodb:27017/
      PORT: 3000
    ports:
      - 3000:3000
    restart: always
    expose:
      - 3000

  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
